pipeline { 
 agent any 
 stages { 
 stage ('Compile Stage') { 
 steps { 
  dir('demo-jenkins') {
 withMaven(maven : 'M2_HOME') { 
 bat 'mvn clean compile' 
 } 
 } 
 } 
 }
 stage('Test') { 
 steps { 
  dir('demo-jenkins') {
 bat 'mvn test' 
 } 
 }
 
 } 
 } 
 }
